spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/test
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true